name = "biabip-backend"
main = "./src/index.ts"
compatibility_date = "2023-10-01"
account_id = "e9c10dfbdee5fb11bf0e2e150d37b8df"
workers_dev = true
# API tokens should not be stored in config files for security reasons

[durable_objects]
bindings = [
  { name = "DATA_STORE", class_name = "DataStore" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DataStore"]

[vars]
JWT_SECRET = "your-jwt-secret-key-change-this-in-production"

[build]
command = "npm install && npm run build"